### ISSUE TITLE
Crashes on Android 2.3

### ISSUE THREAD

**Issue by grassick** [shaithana/cordova-plugin-wezka-nativecamera#11]
getSize is not supported in 2.3

```
E/AndroidRuntime( 2282): java.lang.NoSuchMethodError: android.view.Display.getSize
E/AndroidRuntime( 2282):    at com.wezka.nativecamera.CameraActivity.onCreate(CameraActivity.java:130)
E/AndroidRuntime( 2282):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime( 2282):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1615)
E/AndroidRuntime( 2282):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
```

**Comment by grassick** [comment]
Once that is fixed, fails with:

`W/CameraService(  235): Overlay create failed - retrying`
again and again

then:

```
E/AndroidRuntime( 3019): FATAL EXCEPTION: main
E/AndroidRuntime( 3019): java.lang.RuntimeException: startPreview failed
E/AndroidRuntime( 3019):    at android.hardware.Camera.startPreview(Native Method)
```

http://stackoverflow.com/questions/6612341/overlay-creation-fails-when-starting-camera-preview
