### ISSUE TITLE
Can't find image on Android 4.4.3

### ISSUE THREAD

**Issue by grassick** [shaithana/cordova-plugin-wezka-nativecamera#14]
```
W/System.err( 6830): java.io.FileNotFoundException: No such file or directory
W/System.err( 6830):    at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
W/System.err( 6830):    at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:611)
W/System.err( 6830):    at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:922)
W/System.err( 6830):    at android.content.ContentResolver.openOutputStream(ContentResolver.java:669)
W/System.err( 6830):    at android.content.ContentResolver.openOutputStream(ContentResolver.java:645)
W/System.err( 6830):    at com.wezka.nativecamera.NativeCameraLauncher.onActivityResult(NativeCameraLauncher.java:179)
W/System.err( 6830):    at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:897)
```

**Comment by grassick** [comment]
https://code.google.com/p/android/issues/detail?id=58372

**Comment by shaithana** [comment]
any ideas?

**Comment by grassick** [comment]
One person says: _I explicitly called mkdirs to the path I was trying to save to prior to inserting with the ContentProvider._

What about that? I'm running low on time to look at this more, but if you don't find anything I'll try again in a day or two.

**Comment by shaithana** [comment]
simple, I have not written the code to save the picture on the device, because our app needs that the photo is not saved locally, only sent to the HTML view. Sorry, maybe I'll write in future.

**Comment by grassick** [comment]
It does need to be somewhere on disk when asking for FILE_URI, and it works fine on <= Android 4.2.

**Comment by sbmaggarwal** [comment]
https://code.google.com/p/android/issues/detail?id=75447

I tried this from [this SO answer](http://stackoverflow.com/a/33069416/3913366) and it works:

```
void fixMediaDir() {
    File sdcard = Environment.getExternalStorageDirectory();
    if (sdcard != null) {
        File mediaDir = new File(sdcard, "DCIM/Camera");
        if (!mediaDir.exists()) {
            mediaDir.mkdirs();
        }
    }
}
```
