### ISSUE TITLE
Failure delivering ResultInfo

### ISSUE THREAD

**Issue by grassick** [shaithana/cordova-plugin-wezka-nativecamera#26]
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {co.mwater.clientapp/co.mwater.clientapp.mWater}: java.lang.NullPointerException
  at android.app.ActivityThread.deliverResults(ActivityThread.java:3525)
  at android.app.ActivityThread.handleSendResult(ActivityThread.java:3568)
  at android.app.ActivityThread.access$1100(ActivityThread.java:162)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
  at android.os.Handler.dispatchMessage(Handler.java:107)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5371)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:525)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
  at dalvik.system.NativeStart.main(Native Method)\nCaused by: java.lang.NullPointerException
  at co.mwater.foregroundcameraplugin.ForegroundCameraLauncher.scaleBitmap(ForegroundCameraLauncher.java:271)
  at co.mwater.foregroundcameraplugin.ForegroundCameraLauncher.onActivityResult(ForegroundCameraLauncher.java:198)
  at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:897)
  at android.app.Activity.dispatchActivityResult(Activity.java:5311)
  at android.app.ActivityThread.deliverResults(ActivityThread.java:3521)
  ... 11 more\njava.lang.NullPointerException
  at co.mwater.foregroundcameraplugin.ForegroundCameraLauncher.scaleBitmap(ForegroundCameraLauncher.java:271)
  at co.mwater.foregroundcameraplugin.ForegroundCameraLauncher.onActivityResult(ForegroundCameraLauncher.java:198)
  at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:897)
  at android.app.Activity.dispatchActivityResult(Activity.java:5311)
  at android.app.ActivityThread.deliverResults(ActivityThread.java:3521)
  at android.app.ActivityThread.handleSendResult(ActivityThread.java:3568)
  at android.app.ActivityThread.access$1100(ActivityThread.java:162)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
  at android.os.Handler.dispatchMessage(Handler.java:107)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5371)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:525)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by grassick** [comment]
Oops, this is from an old version of the other plugin. My mistake!
