### ISSUE TITLE
Unable to start activity

### ISSUE THREAD

**Issue by Josephwaelchli** [shaithana/cordova-plugin-wezka-nativecamera#34]
I'm not sure if this is something from my own project being incorrect or a problem with the plug-in but I'd appreciate help in debugging this. When attempting to use the getPicture function the app crashes with this message in log cat 

E/AndroidRuntime( 7280):     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.text2drive.ethereal.dev/com.wezka.nativecamera.CameraActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
E/AndroidRuntime( 7280):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
E/AndroidRuntime( 7280):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
E/AndroidRuntime( 7280):    at android.app.ActivityThread.access$800(ActivityThread.java:139)
E/AndroidRuntime( 7280):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
E/AndroidRuntime( 7280):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7280):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 7280):    at android.app.ActivityThread.main(ActivityThread.java:5086)
E/AndroidRuntime( 7280):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7280):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 7280):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 7280):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 7280):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 7280): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
E/AndroidRuntime( 7280):    at android.content.res.Resources.getValue(Resources.java:1123)
E/AndroidRuntime( 7280):    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2312)
E/AndroidRuntime( 7280):    at android.content.res.Resources.getLayout(Resources.java:939)
E/AndroidRuntime( 7280):    at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
E/AndroidRuntime( 7280):    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime( 7280):    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
E/AndroidRuntime( 7280):    at android.app.Activity.setContentView(Activity.java:1937)
E/AndroidRuntime( 7280):    at com.wezka.nativecamera.CameraActivity.onCreate(CameraActivity.java:91)
E/AndroidRuntime( 7280):    at android.app.Activity.performCreate(Activity.java:5248)
E/AndroidRuntime( 7280):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
E/AndroidRuntime( 7280):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)

it seems like a resource id isn't be set so that when trying to find the activity for the camera it is unable to. I'm not sure if there's an installation step I'm missing or perhaps a file that is not being correctly generated.

**Comment by Josephwaelchli** [comment]
someone who added this plugin did not fully commit their changes, was creating the problem
