### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by mm108** [shaithana/cordova-plugin-wezka-nativecamera#39]
hi,

Firstly thanks a ton for the useful plugin. Can I have a simple / sample code on how to use this plugin? I am totally new to android / java development and learning to add plugins. I am using a Mobile Backend Service for creating my app and it already has the default camera plugin installed. So I just want to make sure that I am starting right

thanks,
M&M

**Comment by mm108** [comment]
hi,

I managed to get it work. Thanks. But one small question - if I want to start the camera with the front camera , where would be the best / correct place to do this?

In CameraActivity.java I changed the 

<pre>
public class CameraActivity extends Activity implements SensorEventListener {
    private static final String TAG = "CameraActivity";
    private SurfaceView preview;
    private SurfaceHolder previewHolder = null;
    private Camera camera = null;
    private boolean inPreview = false;
    private boolean cameraConfigured = false;
    private int led = 0;
    private int cam = 0;
    private boolean pressed = false;
    private int degrees = 0;
    private boolean isFlash = false;
    private boolean isFrontCamera = false; // Changed this to true
    SensorManager sm;
    WindowManager mWindowManager;
</pre>

I changed private boolean isFrontCamera to true. But it does not start with the front camera.

And also I have the following error in the console

<pre>
---> Image: file:///storage/sdcard0/Android/data/io.appery.project287012/cache/Pic-233201514237.jpg
processMessage failed: Error: TypeError: Cannot read property 'style' of null
processMessage failed: Stack: TypeError: Cannot read property 'style' of null
    at onPhotoDataSuccess (file:///android_asset/www/files/views/assets/js/JavaScript1.js:17:15)
    at Object.cordova.callbackFromNative (file:///android_asset/www/files/resources/lib/cordova.js:292:54)
    at processMessage (file:///android_asset/www/files/resources/lib/cordova.js:1053:21)
    at Function.androidExec.processMessages (file:///android_asset/www/files/resources/lib/cordova.js:1090:13)
    at pollOnce (file:///android_asset/www/files/resources/lib/cordova.js:955:17)
    at pollOnceFromOnlineEvent (file:///android_asset/www/files/resources/lib/cordova.js:945:5)
processMessage failed: Message: S01 Camera863742723 sfile:///storage/sdcard0/Android/data/io.appery.project287012/cache/Pic-233201514237.jpg
</pre>

I can see that the image is being created in the folder but I was wondering If I could do anything to fix this error

<pre>
processMessage failed: Error: TypeError: Cannot read property 'style' of null
processMessage failed: Stack: TypeError: Cannot read property 'style' of null
</pre>

Thanks a ton,
M&M

**Comment by mm108** [comment]
hi,

Thanks. I managed to sort that out too. I had misspelt the name of the image element.

Thanks once again,
M&M
