### ISSUE TITLE
Image freezes sometimes

### ISSUE THREAD

**Issue by grassick** [shaithana/cordova-plugin-wezka-nativecamera#4]
I can't reproduce this one, but the preview image displayed freezes sometimes. Locking phone and re-opening does not work, but switching cameras does.

**Comment by grassick** [comment]
Clicking on shutter in this state crashes with:

```
java.lang.RuntimeException: takePicture failed
    at android.hardware.Camera.native_takePicture(Native Method)
E/AndroidRuntime(16983):    at android.hardware.Camera.takePicture(Camera.java:1194)
E/AndroidRuntime(16983):    at android.hardware.Camera.takePicture(Camera.java:1139)
E/AndroidRuntime(16983):    at com.wezka.nativecamera.CameraActivity$4.onClick(CameraActivity.java:239)
E/AndroidRuntime(16983):    at android.view.View.performClick(View.java:4489)
E/AndroidRuntime(16983):    at android.view.View$PerformClick.run(View.java:18803)
E/AndroidRuntime(16983):    at android.os.Handler.handleCallback(Handler.java:730)
```
