### ISSUE TITLE
Wezka Camera Issue in Android 6.0.1

### ISSUE THREAD

**Issue by Vishwa17** [shaithana/cordova-plugin-wezka-nativecamera#47]
Hi Team,

**_While capturing the image , the image is not displaying in the VIEW, I have the following Logcat
Please refer and let me know for more information._**

10-07 07:04:42.010  5918  5918 W ExifInterface: Invalid image.

10-07 07:04:42.010  5918  5918 W ExifInterface: java.io.EOFException

10-07 07:04:42.010  5918  5918 W ExifInterface:     at java.io.DataInputStream.readByte(DataInputStream.java:77)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1599)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at android.media.ExifInterface.loadAttributes(ExifInterface.java:1339)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at android.media.ExifInterface.<init>(ExifInterface.java:1057)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at com.wezka.nativecamera.ExifHelper.createOutFile(ExifHelper.java:83)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at com.wezka.nativecamera.NativeCameraLauncher.onActivityResult(NativeCameraLauncher.java:435)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:320)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at android.app.Activity.dispatchActivityResult(Activity.java:7137)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4916)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4963)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at android.app.ActivityThread.access$1600(ActivityThread.java:221)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at android.os.Handler.dispatchMessage(Handler.java:102)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at android.os.Looper.loop(Looper.java:158)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at android.app.ActivityThread.main(ActivityThread.java:7224)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at java.lang.reflect.Method.invoke(Native Method)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

10-07 07:04:42.010  5918  5918 W ExifInterface:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

10-07 07:04:42.010  5918  5918 I NativeCameraLauncher: Bitmap not compressed

10-07 07:04:42.010  5918  5918 W System.err: java.io.EOFException

10-07 07:04:42.010  5918  5918 W System.err:    at java.io.DataInputStream.readByte(DataInputStream.java:77)

10-07 07:04:42.010  5918  5918 W System.err:    at android.media.ExifInterface.saveJpegAttributes(ExifInterface.java:1730)

10-07 07:04:42.010  5918  5918 W System.err:    at android.media.ExifInterface.saveAttributes(ExifInterface.java:1388)

10-07 07:04:42.010  5918  5918 W System.err:    at com.wezka.nativecamera.ExifHelper.writeExifData(ExifHelper.java:180)

10-07 07:04:42.010  5918  5918 W System.err:    at com.wezka.nativecamera.NativeCameraLauncher.onActivityResult(NativeCameraLauncher.java:436)

10-07 07:04:42.010  5918  5918 W System.err:    at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)

10-07 07:04:42.010  5918  5918 W System.err:    at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:320)

10-07 07:04:42.010  5918  5918 W System.err:    at android.app.Activity.dispatchActivityResult(Activity.java:7137)

10-07 07:04:42.010  5918  5918 W System.err:    at android.app.ActivityThread.deliverResults(ActivityThread.java:4916)

10-07 07:04:42.010  5918  5918 W System.err:    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4963)

10-07 07:04:42.010  5918  5918 W System.err:    at android.app.ActivityThread.access$1600(ActivityThread.java:221)

10-07 07:04:42.010  5918  5918 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)

10-07 07:04:42.010  5918  5918 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)

10-07 07:04:42.010  5918  5918 W System.err:    at android.os.Looper.loop(Looper.java:158)

10-07 07:04:42.010  5918  5918 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7224)

10-07 07:04:42.010  5918  5918 W System.err:    at java.lang.reflect.Method.invoke(Native Method)

10-07 07:04:42.010  5918  5918 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

10-07 07:04:42.010  5918  5918 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

10-07 07:04:42.010  5918  5918 I NativeCameraLauncher: failPicture:Error compressing image

**Comment by yaashvisoftware** [comment]
Facing the same issue in Android 6.0.1.

**Comment by Vishwa17** [comment]
I have solve this issue

**Comment by craftpip** [comment]
@Vishwa17 How did you fix it? please provide some answer to others who face it.
